import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/src/components/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Cagir.az</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Sifarisi yarat duymesi ve karusel </h1>
        <h1>Xidmetler hamisi </h1>
        <h1>Musteri reyleri </h1>
        <h1>Tez-tez verilen suallar </h1>
        <h1>Kampaniyalar </h1>
        <h1>Deyerler </h1>
        <h1>Bloq/Kartlar </h1>
      </main>
    </>
  );
}
