import Head from "next/head";
import { Inter } from "next/font/google";
import Carousel1 from "@/src/components/carousel/carousel1";
import Xidmetler from "@/src/components/xidmetler/xidmetler";
import Reyler from "@/src/components/reyler/reyler";
import Icracilar from "@/src/components/icraci/icraci";
import Suallar from "@/src/components/suallar/suallar";
import Deyerler from "@/src/components/deyerler/deyerler";
import Bloq from "@/src/components/bloq/bloq";
import Partnyorlar from "@/src/components/partnyorlar/partnyorlar";
import TabBar from "@/src/components/mobile/tab_bar";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const data = await import("/data/data.json");
  const {
    xidmetler,
    icracilar,
    suallar,
    reyler,
    bloqlar,
    carouselPhotos1,
    partnyorlar,
  } = data;
  return {
    //will be passed to the page component as props
    props: {
      xidmetler,
      icracilar,
      suallar,
      reyler,
      bloqlar,
      carouselPhotos1,
      partnyorlar,
    },
  };
}

export default function Home(props) {
  const {
    icracilar,
    xidmetler,
    suallar,
    reyler,
    bloqlar,
    carouselPhotos1,
    partnyorlar,
  } = props;

  return (
    <div>
      <Head>
        <title>Cagir.az</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="space-y-[30px] desktop:space-y-[135px]">
        {/* <Carousel1 {...{ carouselPhotos1 }} /> */}
        <Xidmetler {...{ xidmetler }} />
        <Reyler {...{ reyler }} />
        <Icracilar {...{ icracilar }} />
        {/*<Partnyorlar {...{ partnyorlar }} />
        <Suallar {...{ suallar }} />
        <Deyerler />
        <Bloq {...{ bloqlar }} /> */}
        <TabBar />
      </main>
    </div>
  );
}
